# @sprintId =
@userId = 4

###
# GET ALL SPRINTS
GET http://localhost:8000/api/sprints/

###
# GET ONE SPRINT
GET http://localhost:8000/api/sprints/2/

###
# POST A NEW SPRINT
POST http://localhost:8000/api/sprints/
Content-Type: application/json

{
  "sprintName": "extra goal"
} 

###

POST http://localhost:8000/api/sprints/1/sprint-goals/
Content-Type: application/json

{
  "goalName": "extra goal",
  "goalDescription": "lalala"
} 

### 

# REGISTER A NEW USER
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "name": "Chloe",
  "username": "Chloe",
  "email": "chloe@email.com",
  "password": "password",
  "passwordConfirmation": "password",
  "avatar": "image.jpg"
}

###

# LOGIN A USER
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "chloe@email.com",
  "password": "password"
}

###

# GET USERS PROFILE
GET http://localhost:8000/api/auth/profile/{{userId}}/

###

# GET ALL SPRINTS
GET http://localhost:8000/api/sprints/

###


# POST A SPRINT GOAL
POST http://localhost:8000/api/sprints/1/sprint-goals/
Content-Type: application/json

{
  "goalName": "extra goal",
  "goalDescription": "lalala"

} 
###
# DELETE A SPRINT GOAL

###

# POST A SPRINT HABIT
POST http://localhost:8000/api/sprints/1/sprint-habits/
Content-Type: application/json

{
  "goalName": "extra goal",
  "goalDescription": "lalala"

} 
###
# DELETE A SPRINT HABIT







### ADD A WEEKLY INTENTION

### 
# GET ALL DAILY TO-DOs
GET http://localhost:8000/api/sprints/daily-to-dos/

### 
# ADD DAILY TO-DO
POST http://localhost:8000/api/sprints/1/daily-to-dos/1
Content-Type: application/json

{
  "toDoItem": "extra goal"
} 
### 
# DELETE DAILY TO-DO

### ADD DAILY GRATITUDE
