@userId = 1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImV4cCI6MTYyNDY1OTgwNX0.dfcADNkLB0A8ctSv2sCYnvotz3aFrV05Vd6xADxcfkM
@sprintId = 4
@goalId = 1
@habitId = 1
@intentionId = 1
@toDoId = 1
@moodId = 1
@energyLevelId = 1
@gratitudeId = 1

######################################### USER REQUESTS ###############################################
### 

# REGISTER A NEW USER
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "name": "el",
  "username": "el",
  "email": "el@email.com",
  "password": "pass",
  "passwordConfirmation": "pass",
  "avatar": "image.jpg",
  "city": "London"
}

###

# LOGIN A USER
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "el@email.com",
  "password": "pass"
}

###
# GET A USER'S PROFILE
GET http://localhost:8000/api/auth/profile/{{userId}}/

###
# CHECK USER SPRINT FOR RESET
PUT http://localhost:8000/api/auth/profile/{{userId}}/reset/


######################################### SPRINT REQUESTS ###############################################

###
# GET ALL SPRINTS
GET http://localhost:8000/api/sprints/

###
# POST A NEW SPRINT
POST http://localhost:8000/api/sprints/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sprintName": "my new sprint"
} 

###
# GET ONE SPRINT
GET http://localhost:8000/api/sprints/{{sprintId}}/

### !! ERROR !!
# # DELETE A SPRINT
# DELETE http://localhost:8000/api/sprints/{{sprintId}}/

# Content-Type: application/json

### !! ERROR !!
# UPDATE A SPRINT
# PUT http://localhost:8000/api/sprints/{{sprintId}}/

# Content-Type: application/json
# # Authorization: Bearer {{token}}

# {
#   "sprintName": "alara hates sprinting"
# } 

################################### SPRINT HABIT/GOAL REQUESTS ##########################################


///////////////// SPRINT GOAL REQUESTS /////////////////
###
# GET ALL SPRINT GOALS
GET http://localhost:8000/api/sprints/{{sprintId}}/sprint-goals/
Content-Type: application/json

###
# POST A SPRINT GOAL
POST http://localhost:8000/api/sprints/{{sprintId}}/sprint-goals/
Content-Type: application/json

{
  "goalName": "my second goal",
  "goalDescription": "make it beautiful!"

} 

###
# GET A SPRINT GOAL
GET http://localhost:8000/api/sprints/{{sprintId}}/sprint-goals/{{goalId}}/


###
# DELETE A SPRINT GOAL
DELETE http://localhost:8000/api/sprints/{{sprintId}}/sprint-goals/{{goalId}}/


###
# UPDATE A SPRINT GOAL
PUT http://localhost:8000/api/sprints/{{sprintId}}/sprint-goals/{{goalId}}/
Content-Type: application/json

{
  "goalName": "extra goal",
  "goalDescription": "lalala"

} 

///////////////// SPRINT HABIT REQUESTS /////////////////
###
# GET ALL SPRINT HABITS
GET http://localhost:8000/api/sprints/{{sprintId}}/sprint-habits/
Content-Type: application/json

###
# POST A SPRINT HABIT
POST http://localhost:8000/api/sprints/{{sprintId}}/sprint-habits/
Content-Type: application/json

{
  "habitName": "huh has a habit",
  "habitDescription": "lalala"

} 

###
# GET A SPRINT HABIT
GET http://localhost:8000/api/sprints/{{sprintId}}/sprint-habits/{{habitId}}/
Content-Type: application/json

###
# DELETE A SPRINT HABIT
DELETE http://localhost:8000/api/sprints/{{sprintId}}/sprint-habits/{{habitId}}/
Content-Type: application/json

###
# UPDATE A SPRINT HABIT
PUT http://localhost:8000/api/sprints/{{sprintId}}/sprint-habits/{{habitId}}/
Content-Type: application/json

{
  "habitName": "extra habit",
  "habitDescription": "lalala"

} 


######################################### WEEKLY REQUESTS ###############################################

###
# GET ALL WEEKLY INTENTIONS
GET http://localhost:8000/api/sprints/{{sprintId}}/intentions/
Content-Type: application/json

###
# POST A WEEKLY INTENTION
POST http://localhost:8000/api/sprints/{{sprintId}}/intentions/
Content-Type: application/json

{
  "weeklyIntention": "We will get this project done"
} 

###
# DELETE A WEEKLY INTENTION
DELETE http://localhost:8000/api/sprints/{{sprintId}}/intentions/{{intentionId}}/
Content-Type: application/json

###
# UPDATE A WEEKLY INTENTION
PUT http://localhost:8000/api/sprints/{{sprintId}}/intentions/{{intentionId}}/
Content-Type: application/json

{
  "weeklyIntention": "We WILL get this project done"
} 


######################################### DAILY REQUESTS ###############################################


///////////////// TO-DO REQUESTS /////////////////
###
# GET ALL TO-DOs
GET http://localhost:8000/api/sprints/{{sprintId}}/to-dos/
Content-Type: application/json

###
# POST A TO-DO
POST http://localhost:8000/api/sprints/{{sprintId}}/to-dos/
Content-Type: application/json


{
  "toDoItem": "Finish backend"
} 

###
# DELETE A TO-DO
DELETE http://localhost:8000/api/sprints/{{sprintId}}/to-dos/{{toDoId}}/
Content-Type: application/json

###
# UPDATE A TO-DO
PUT http://localhost:8000/api/sprints/{{sprintId}}/to-dos/{{toDoId}}/
Content-Type: application/json

{
  "toDoItem": "Start frontend"
} 


///////////////// MOOD REQUESTS /////////////////
###
# GET ALL MOODS
GET http://localhost:8000/api/sprints/{{sprintId}}/moods/
Content-Type: application/json

###
# POST A MOOD
POST http://localhost:8000/api/sprints/{{sprintId}}/moods/
Content-Type: application/json

{
  "moodName": "Kaput"
} 

###
# DELETE A MOOD
DELETE http://localhost:8000/api/sprints/{{sprintId}}/moods/{{moodId}}/
Content-Type: application/json



///////////// ENERGY LEVEL REQUESTS ////////////
###
# GET ALL ENERGY LEVELS
GET http://localhost:8000/api/sprints/{{sprintId}}/energy-levels/
Content-Type: application/json

###
# POST AN ENERGY LEVEL
POST http://localhost:8000/api/sprints/{{sprintId}}/energy-levels/
Content-Type: application/json

{
  "energyLevel": 1
} 

###
# DELETE AN ENERGY LEVEL
DELETE http://localhost:8000/api/sprints/{{sprintId}}/energy-levels/{{energyLevelId}}/
Content-Type: application/json

###
# UPDATE AN ENERGY LEVEL
PUT http://localhost:8000/api/sprints/{{sprintId}}/energy-levels/{{energyLevelId}}/
Content-Type: application/json

{
  "energyLevel": 4
} 

////////////// GRATITUDE REQUESTS /////////////
###
# GET ALL GRATITUDES
GET http://localhost:8000/api/sprints/{{sprintId}}/gratitudes/
Content-Type: application/json

###
# POST A GRATITUDE
POST http://localhost:8000/api/sprints/{{sprintId}}/gratitudes/
Content-Type: application/json

{
  "dailyGratitude": "coffee"
} 

###
# DELETE A GRATITUDE
DELETE http://localhost:8000/api/sprints/{{sprintId}}/gratitudes/{{gratitudeId}}/
Content-Type: application/json

###
# UPDATE A GRATITUDE
PUT http://localhost:8000/api/sprints/{{sprintId}}/gratitudes/{{gratitudeId}}/
Content-Type: application/json

{
  "dailyGratitude": "Still coffee"
} 


