# Generated by Django 3.2.4 on 2021-06-16 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='user',
        ),
        migrations.AddField(
            model_name='sprint',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_sprints', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
