# Generated by Django 3.2.4 on 2021-06-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintgoal',
            name='goal_description',
        ),
    ]
