# Generated by Django 3.2.4 on 2021-06-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_remove_sprintgoal_goal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintgoal',
            name='is_done',
        ),
    ]
