# Generated by Django 3.2.4 on 2021-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20210614_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_item', models.CharField(max_length=40)),
                ('isDone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_item', models.CharField(max_length=40)),
                ('isDone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
