# Generated by Django 3.2.4 on 2021-06-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_remove_sprintgoal_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprinthabit',
            name='habit_description',
        ),
    ]
