# Generated by Django 3.2.4 on 2021-06-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_auto_20210614_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyintention',
            name='weekly_intention',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyGratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_gratitude', models.CharField(max_length=200)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_gratitude', to='sprints.sprint')),
            ],
        ),
    ]
