# Generated by Django 3.2.4 on 2021-06-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_mood_sprintgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='mood_image',
        ),
    ]
