# Generated by Django 3.2.4 on 2021-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(default='password', max_length=25),
            preserve_default=False,
        ),
    ]
