# Generated by Django 3.2.4 on 2021-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20210615_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_confirmation',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
