# Generated by Django 3.2.4 on 2021-06-16 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('sprint', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='energy_levels', to='sprints.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint')),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='sprint',
        ),
        migrations.AddField(
            model_name='dailygratitude',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyintention',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytodo',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to='sprints.sprint'),
        ),
        migrations.DeleteModel(
            name='Energy',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
