# Generated by Django 3.2.4 on 2021-06-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SprintGoals',
            new_name='SprintGoal',
        ),
    ]
