# Generated by Django 3.2.4 on 2021-06-15 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_dailytodo_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SprintHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_item', models.CharField(max_length=50)),
                ('habit_description', models.CharField(max_length=250)),
                ('isDone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='end_date',
        ),
        migrations.AddField(
            model_name='sprintgoal',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goals', to='sprints.sprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint'),
        ),
    ]
