# Generated by Django 3.2.4 on 2021-06-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0009_auto_20210615_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='energy_level',
        ),
    ]
