# Generated by Django 3.2.4 on 2021-06-15 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0017_auto_20210615_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintgoal',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
