# Generated by Django 3.2.4 on 2021-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0006_alter_dailygratitude_sprint'),
        ('sprints', '0006_auto_20210615_0950'),
        ('sprints', '0018_sprintgoal_end_date'),
    ]

    operations = [
    ]
