# Generated by Django 3.2.4 on 2021-06-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyenergy',
            name='sprint',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_levels', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='dailygratitude',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_gratitudes', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='dailymood',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='dailytodo',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goals', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='sprinthabit',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_habits', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='weeklyintention',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_intentions', to='sprints.sprint'),
        ),
    ]
