# Generated by Django 3.2.4 on 2021-06-14 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_rename_sprintgoals_sprintgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sprintgoal',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeeklyIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_intentions', to='sprints.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint')),
            ],
        ),
        migrations.AddField(
            model_name='sprintgoal',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goals', to='sprints.sprint'),
        ),
    ]
