# Generated by Django 3.2.4 on 2021-06-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20210614_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goals', to='sprints.sprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyintention',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_intentions', to='sprints.sprint'),
            preserve_default=False,
        ),
    ]
