# Generated by Django 3.2.4 on 2021-06-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20210614_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SprintGoal',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='start_date',
        ),
    ]
