# Generated by Django 3.2.4 on 2021-06-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_auto_20210614_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('goal_description', models.CharField(max_length=250)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goals', to='sprints.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
                ('mood_image', models.CharField(max_length=250)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='sprints.sprint')),
            ],
        ),
    ]
