# Generated by Django 3.2.4 on 2021-06-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20210615_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygratitude',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_gratitudes', to='sprints.sprint'),
        ),
    ]
