# Generated by Django 3.2.4 on 2021-06-15 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20210615_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytodo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dailytodo',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_to_do', to='sprints.sprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytodo',
            name='to_do_item',
            field=models.CharField(max_length=50),
        ),
    ]
