# Generated by Django 3.2.4 on 2021-06-15 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0008_auto_20210615_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='energy_name',
        ),
        migrations.AddField(
            model_name='energy',
            name='energy_level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energy',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_levels', to='sprints.sprint'),
        ),
    ]
