# Generated by Django 3.2.4 on 2021-06-15 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0012_auto_20210615_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 10, 51, 34, 162277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 10, 51, 34, 162079, tzinfo=utc)),
        ),
    ]
