# Generated by Django 3.2.4 on 2021-06-15 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0014_auto_20210615_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 10, 55, 46, 400989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 10, 55, 46, 400798, tzinfo=utc)),
        ),
    ]
