# Generated by Django 3.2.4 on 2021-06-15 11:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0015_auto_20210615_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 11, 3, 23, 278095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 11, 3, 23, 277906, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField(verbose_name=datetime.datetime(2021, 6, 15, 11, 3, 23, 278264, tzinfo=utc))),
                ('sprint', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='energy_levels', to='sprints.sprint')),
            ],
        ),
    ]
