# Generated by Django 3.2.4 on 2021-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0016_auto_20210615_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sprintgoal',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
